[build]
  publish = "."

[[headers]]
  for = "/dados/*"
  [headers.values]
    Content-Disposition = "attachment"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"
